In [1]:
from __future__ import division
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress=True)

In [2]:

data = randn(2, 3)

In [3]:
data

array([[-0.0466, -1.3712, -0.5232],
       [ 0.3361, -0.2065,  0.1538]])

In [4]:
print data

[[-0.0466 -1.3712 -0.5232]
 [ 0.3361 -0.2065  0.1538]]


In [5]:
print (data)

[[-0.0466 -1.3712 -0.5232]
 [ 0.3361 -0.2065  0.1538]]


In [6]:
data
data * 10
data + data

array([[-0.0931, -2.7423, -1.0463],
       [ 0.6722, -0.4129,  0.3075]])

In [8]:
data.shape


(2, 3)

In [9]:
data.dtype

dtype('float64')

In [10]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [11]:

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.shape

(2, 4)

In [14]:
arr2.dtype

dtype('int32')

In [20]:
np.zeros(10)


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [21]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [22]:
np.empty((2, 3, 2))

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [23]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [25]:
arr2.dtype

dtype('int32')

In [26]:
arr1

array([ 1.,  2.,  3.])